CC=gcc
CFLAGS=-Iinclude

SRC=src/main.c src/route.c
OBJ=$(SRC:.c=.o)

TARGET=bin/program

all: $(TARGET)

$(TARGET): $(SRC)
	mkdir -p bin
	$(CC) $(SRC) -o $(TARGET) $(CFLAGS)

clean:
	rm -rf bin/*.o bin/program
